// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  var MoviePanel;

  this.movieApp = angular.module('movieApp', []);

  MoviePanel = (function() {
    function MoviePanel($scope, $http) {
      var searchNum;
      this.$scope = $scope;
      this.$http = $http;
      $scope.searchInput = "";
      $scope.movieList = [];
      $scope.movieDetails = void 0;
      $scope.movieInfoInvisible = true;
      searchNum = 0;
      $scope.search = function(movie) {
        $scope.movieInfoInvisible = true;
        return $http({
          url: "http://www.omdbapi.com/",
          method: "get",
          params: {
            s: movie
          }
        }).success(function(data, status, headers, config) {
          $scope.movieList = data.Search;
          return console.log($scope.movieList);
        }).error(function(data, status, headers, config) {
          return $scope.status = status;
        });
      };
      $scope.showDetails = function(movie) {
        $scope.movieInfoInvisible = false;
        return $http({
          url: "http://www.omdbapi.com/",
          method: "get",
          params: {
            i: movie.imdbID
          }
        }).success(function(data, status, headers, config) {
          $scope.movieDetails = data;
          return console.log($scope.movieDetails);
        }).error(function(data, status, headers, config) {
          return $scope.status = status;
        });
      };
    }

    return MoviePanel;

  })();

  MoviePanel.$inject = ["$scope", "$http"];

  movieApp.controller("MoviePanel", MoviePanel);

}).call(this);
