// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  var MoviePanel;

  this.movieApp = angular.module('movieApp', []);

  MoviePanel = (function() {
    function MoviePanel($scope, $http) {
      this.$scope = $scope;
      this.$http = $http;
      $scope.searchInput = "matrix";
      $scope.loadingGif = true;
      $scope.search = function() {
        var results, searchTerm;
        console.log($scope.searchInput);
        if ($scope.searchInput) {
          $scope.movieList = [];
          $scope.loadingGif = false;
          searchTerm = $scope.searchInput;
          console.log(searchTerm);
          $http({
            url: "http://www.omdbapi.com/",
            method: "get",
            params: {
              s: searchTerm
            }
          }).success(function(data, status, headers, config) {
            console.log("data: " + data + "status: " + status + "headers:" + headers + "config: " + config);
            return results(data);
          }).error(function(data, status, headers, config) {
            return $scope.status = status;
          });
          return results = function(data) {
            var movie, _i, _len, _ref, _results;
            $scope.loadingGif = true;
            if (data.Response !== 'False') {
              $scope.movieList = [];
              _ref = data["Search"];
              _results = [];
              for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                movie = _ref[_i];
                console.log(movie);
                console.log(movie.Title);
                _results.push($scope.movieList.push(movie));
              }
              return _results;
            }
          };
        }
      };
    }

    return MoviePanel;

  })();

  MoviePanel.$inject = ["$scope", "$http"];

  movieApp.controller("MoviePanel", MoviePanel);

}).call(this);
