// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  var MoviePanel;

  this.movieApp = angular.module('movieApp', []);

  MoviePanel = (function() {
    function MoviePanel($scope, $http) {
      this.$scope = $scope;
      this.$http = $http;
      $scope.searchInput = "matrix";
      $scope.loadingGif = true;
      $scope.dropDownInvisible = true;
      $scope.movieInfoInvisible = true;
      $scope.search = function() {
        var results, searchTerm;
        console.log($scope.searchInput);
        if ($scope.searchInput) {
          $scope.movieList = [];
          $scope.loadingGif = false;
          $scope.dropDownInvisible = true;
          searchTerm = $scope.searchInput;
          console.log(searchTerm);
          $http({
            url: "http://www.omdbapi.com/",
            method: "get",
            params: {
              s: searchTerm
            }
          }).success(function(data, status, headers, config) {
            console.log("data: " + data + "status: " + status + "headers:" + headers + "config: " + config);
            return results(data);
          }).error(function(data, status, headers, config) {
            return $scope.status = status;
          });
          return results = function(data) {
            var movie, _i, _len, _ref, _results;
            $scope.loadingGif = true;
            if (data.Response !== 'False') {
              $scope.movieList = [];
              $scope.dropDownInvisible = false;
              _ref = data["Search"];
              _results = [];
              for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                movie = _ref[_i];
                console.log(movie);
                console.log(movie.Title);
                _results.push($scope.movieList.push(movie));
              }
              return _results;
            }
          };
        }
      };
      $scope.searchPick = function($event, movie) {
        var imdbInfo;
        $scope.movieInfo = {};
        $scope.dropDownInvisible = true;
        console.log("Working!");
        console.log($event, movie);
        console.log(movie.imdbID);
        $scope.movieInfoInvisible = false;
        $http({
          url: "http://www.omdbapi.com/",
          method: "get",
          params: {
            i: movie.imdbID
          }
        }).success(function(data, status, headers, config) {
          console.log("data: " + data + "status: " + status + "headers:" + headers + "config: " + config + "imdbID: " + movie.imdbID);
          return imdbInfo(data);
        }).error(function(data, status, headers, config) {
          return $scope.status = status;
        });
        return imdbInfo = function(data) {
          var info, key;
          console.log("This is the data " + data.Title);
          for (key in data) {
            info = data[key];
            $scope.movieInfo[key] = info;
            console.log(key, info);
          }
          return console.log($scope.movieInfo);
        };
      };
    }

    return MoviePanel;

  })();

  MoviePanel.$inject = ["$scope", "$http"];

  movieApp.controller("MoviePanel", MoviePanel);

}).call(this);
