// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  var MoviePanel;

  this.movieApp = angular.module('movieApp', []);

  MoviePanel = (function() {
    function MoviePanel($scope, $http) {
      var data, results, searchTerm;
      this.$scope = $scope;
      this.$http = $http;
      searchTerm = "";
      data = {};
      results = {};
      $scope.search = function() {
        return searchTerm = $("input").val();
      };
      $http({
        url: "http://www.omdbapi.com/",
        method: "get",
        data: {
          s: searchTerm
        },
        dataType: "json"
      }).success(function(data, status, headers, config) {
        return results(data);
      }).error(function(data, status, headers, config) {
        return $scope.status = status;
      });
      results(data)(function() {
        var li, movie, _i, _len, _ref, _results;
        _ref = data["Search"];
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          movie = _ref[_i];
          console.log(data);
          console.log(movie.Title);
          li = $("<li>" + movie.Title + "</li>");
          _results.push($(".result").append(li));
        }
        return _results;
      });
    }

    return MoviePanel;

  })();

  MoviePanel.$inject = ["$scope", "$http"];

  movieApp.controller("MoviePanel", MoviePanel);

}).call(this);
